---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - crd.chowki.events.io
  resources:
  - chowkidars
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - crd.chowki.events.io
  resources:
  - chowkidars/finalizers
  verbs:
  - update
- apiGroups:
  - crd.chowki.events.io
  resources:
  - chowkidars/status
  verbs:
  - get
  - patch
  - update
